fix(ui) : Tactical Overview it appears in black
centreon/centreon-widget-tactical-overview pull request #56
Opened 2022-05-09 11:12 UTC by hyahiaoui-ext

## Description

Tactical overview style was not applied because of css link "type" attribute was missing.

**Fixes** # MON-13241

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 20.10.x
- [ ] 21.04.x
- [ ] 21.10.x
- [x] 22.04.x (master)

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2022-05-10 06:24 UTC, kduret commented on tactical-overview/index.php
> -    $variablesThemeCSS = match ($centreon->user->theme) {
not needed ?

2022-05-10 14:20 UTC, callapa requested changes

2022-05-11 07:03 UTC, kduret approved these changes

2022-05-11 07:03 UTC, jeremyjaouen approved these changes

2022-05-12 09:49 UTC, callapa approved these changes

2022-05-12 11:03 UTC, merged